services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Brussels
      - VERSION=docker
    volumes:
      - ./config:/config
      - ./tmp:/tmp
      - hetzner:/hetzner
      - nas:/nas
    restart: unless-stopped

volumes:
  hetzner:
    driver: local
    driver_opts:
      type: cifs
      device: "//server/ip/share"
      o: "username=example,password=example,uid=0,gid=0"

  nas:
    driver: local
    driver_opts:
      type: nfs
      o: addr=server/ip,rw,vers=4
      device: ":/volume1/media"