services:
  gitea:
    image: gitea/gitea:latest 
    container_name: gitea-server
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${POSTGRES_HOST:-gitea-db}:${POSTGRES_PORT:-5432}
      - GITEA__database__NAME=${POSTGRES_DB:?POSTGRES_DB not set}
      - GITEA__database__USER=${POSTGRES_USER:?POSTGRES_USER not set}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      - GITEA__server__SSH_PORT=2222
      - GITEA__server__ROOT_URL=https://git.nuthub.io
      - GITEA__SSH__MINIMUM_KEY_SIZES
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    restart: unless-stopped
    network_mode: main

  gitea-db:
     image: postgres:latest
     container_name: gitea-db
     environment:
       - POSTGRES_USER=${POSTGRES_USER:?POSTGRES_USER not set}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
       - POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB not set}
     network_mode: main
     volumes:
       - ./postgres:/var/lib/postgresql/data
     restart: unless-stopped